env:
  global:
    - secure: ISUFplU3pj/S86uXczherVApZk0CXQ3iFu24x+oXQlfPiAL3gM/2i2m2xtXDHBTeOoAvC+XoSH4vOCqNOjOVW+zS2dOffg8Wk6MbYc174DbR/6V8as+5Q9F1ahdENecpqXeei+ZyWmCgNZMCJrcR2Gawh8/B66g3nd+q0J5HngP4thRbu6I/JX6fhtr9dN1Nb/61/BTCMycKhA8fikaIk537Y+WlsF0yTxoaIAmf3XKGk1+v7wXn+ufrSezIneVrD/v54P3LbqEdz6ajnalFBviUCanilu0P3KTlPewK3ck+BarUcHt2b7qRc6JvCNatRUYy/zK2BR0zyS70mHz9qXAyjb0jr8PdnybQqzw5+lVTN5MuY7MvoPsZDD5UhLwHkVgEkY97vATeQUnkVQAmCxqnRm9d7ffp+YPz4n8m25gxtbOA9tuGwU7QBvKvP/ffcAucUyyUQN8f4WaPZGA9NBadgMXfcf0OI2zNMspnAyTHm5J++5mdT8MIi8hJj909Cm2GkCIweit6A31+Zch8BZd83hUa9pDcGLt47FhfkI+pyaHzNVw9eUa/qSM3TNzcSGsW2CATwIs+ZBvUUeTAffgUXRegTr+VU+X4BlhWrC/7IYsuZnL/D/2dUMylTq9BsnZQZcx/u//TchKHksSl5VAOEcUgYp1HL0WOwhNdHoI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
