env:
  global:
    - secure: lwfsAKOF2R5PtRH8BCMhjkv10QQU7Ml4DvvYuLCRlhObqQ8UsmAdfEvxZ3ukgvgcX6FnJYQw8FWgwvKBQkT755oxv1MHCd3FaKprrs/pCM03bpmuzqkbP+jM4GXtA7g9fxb8ZWB1pb3c1QdVQ02/qzezhy3CtKvElL6YbKI+lb+CX/1KrkpA43BhSsXkPHwhA5MAeROh5ajARX9ZaAVeQSb0dVaGNi05gCceuoo+r3HuTTPG6K8T9YNour18/CYpGKrrubDmG1INAc2vhM0imb5yPni4CZJPPxPXvLYdW3xa4mr5iJJdYL9yjGAutwmvGRL51ZktuSrS86qu1oQx9YiKIOTQshMfl8E4J5oHEgD56s71441bbOdTlqbrtSEeanHD87CBVEzejJxo0sVUIO8Pn6CJztMJW8YH4sRHTy8WPGecjoQHsAm6IXI/Zctil+e3mFK/m++tyShg34lTaTsh1y6J04HwAlT0utitT0LDC4cYK6AlxNvPmj/S8mXRA5ZyDG9hYhPrFznO2cYG9T8zlLWyV0s6osDImM+RlZYDgy4eYNWR6ECuKtykyeNGhI2MPsFW4f42vnlJDT/Wi9SySI2B/g5dG1cC1HsdrgSkqBAMgXft/Zi/DmLlaIa6jO9QxgEezaqKzkPuFSg2nOGPnuBsCv/DXsCUuEulW78=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
