env:
  global:
    - secure: Dw8j8vFLPPgn+37KbAw92BIE2xhhJzGyjUTZtXtliNWC3Bv9yEyCNTBvzmgbTLDZTzIW5CyGE/pL0Cm7Wiw0IiUAeyWgSHarp6bRoguH7CMVyKXU5kTh3i387riizxTryvFHD0OOeNwAX5lNjenSAT0l04vMaVvNDjZLjpT7adxrjv/i6f7I8xW6459AEQX9dZOMXZIeE29II/URTPSJOb/1DSJ2fvmg9urgSFrLuIQ7CsXjtbCOXLaD3NRYD6MUXf26JDGWIyMTn6MeiWghp+ZcwvAN0XeRPdFjij/D7Yr23nOm3e8O0rYxD6oPpG/yj3fdHsK2WdyFv4IjHKShH5b5TxXjpWRaob3UMhKKRtujgYLFzhqn+Hk5zuz6gAbEUTwC5qYWkkvdi4cMJiEH9ljFZk0tQL0/cEClSStIQRF0w8BiJzGXlLnHV852OP3coOHTKl40FSCJip0iY/VSJ+DG4z6WBiwqpyMjBS8KUr49wq6KpPYfU1ugSBzjBVIJugfWelSmXaTBsQxFgoPKIWSw/O3DxRDANOqNJoM3uUTt4tjbbD0syYU4Pw9upZ51lIgzJ7wJWl9YC7hTEzuGM8sBDmTLvatR5dKLoFhCklzsnTqXZ50+7lYcsvQzS7X29gGP/rCOst/9jtj0/bMcuGcoimNI1dvbmAwxsCPF11I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
