env:
  global:
    - secure: dKlFzMDhpAA58zKlK8kZNbL/wEACg/a9rVFCwyT3mqrii7KMhvPZoOwk4vstsM+DPJuoJjL6DGv8seS1vEnL1uD+XDgxcpHXywoTWFL+CAyOLEBiZo/xLRZ5tzTi9pSIhBYkTdmANApjnFV68n3XBBkY5LYi9uw6IyzGkCtt6wBZi1UARZsVEjrp1lZPS2ALgB3YooPFOVz3KWNtZIn0e3eeprX6p/8p08Pqdt172esgazDCeNvHd/T1ZeysZiGAzHx3ExKCXhKLM9YW5RCWnlbupg7IeMG3iyMFKEDqG4KV3STgkyG3ZmFgAl2myxtoqrHFSsYEkqu+JyTNMvWh/F68oxzPLo4fstHPS1Ab3Gw57zefBJrG0ZZR613kZUmjRtt5QZORDega2CIjvmpiJNZsHwg5ILE6BeoA5RWD3NV5dKDVrcVj/SoglurYD4h3005c4OSXxWsb4sEUHP6qokXf/IXKg8KyssW5drol8MDcPLaVY77BX3D9DGMYcASRuXXWaHHTrGykVZZ+ft4CgRwpb0OTlGsGNONCT21jDOtVjESSNeEvHxqwKtMLtSXZkVqTCS8wkka47dCAAEYiJ/RpHd9NLycOU+iEA5E5C+8mKIcREY7220+TNbHmLA4kb0sUK9T4ROiUFqBVVpM9b7iMZAs4+VsXBQ2jM+n8zAE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
