env:
  global:
    - secure: ZA9r98adhKMIm4PJKjFRRkLRnQzp65j44cw/dww3mzFTzrJZgVMnal34m4nX88tuDYuaNDIfG48CjatXa4PjG1yJgMEj2gQXqvfanQ7BdPlZ0JLbdTbDgWPnIMP06v1D+A6cNLS08EI2ifLNAMBfeDSH9es13J3MQ/KNJEjHYKv0B39oKJCE3CtOXmBqy8qTa0WXu4VxyzXOe46riKoId5s5JKsFwiqtRu3Ecfpy5j2k7hTcpMSuvxH646yHaac1vhZtfz8uDv37/tUKNqb+1kGOrC3FzzgP0CcwGHnwXmqTBHqvYEklfiu0F+ypdwQNPzFxosCK+7UKOaYZPh7TRG1GY7a637LWUYjvRgSmU1MSKu5Gf/pB56nHlTxvqfyNgNqgBLc/KPD9o9vQ5COynwcxzbBjSQy+s+smmx5JrI5Jx+Il/ivimF0t8F26jj63Ojwkbis9K5JrBZhg2XjeGau69WLtjlIT/H3EpCjReVgcSfhMHaSO0F+D/bhnJgnmBKYp2rSZ6YxHO/ZeG6vz3xqcCKi7Vg/I9DHP0kYUQ+wJ55uYFE+5uiAQSRWuKGHfgjbcUGhuO2BuKt57STr6UaDYDXdGVrRWpDGgkmnHtNU7VA0U8HpZbNydd3ENwOtni23Ig6Nx19vgc7M90lQ60nCC3+Cb0h/lENESsQYVztk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
