env:
  global:
    - secure: P7QtKb1UHowsdLoJV5dmu7C+Mt8ROEsQyAp4XBwW6UgQYKcfJ0W/K0ye0pc1m9uS0EIOI49o8LHabsxwTvCHGxFqrghsb22O0/V3FpffnWC/WhuTJ+MDwcV+gIpc56jXWQQDITPy+Fv/2hphehxP3nU9cqg7sa05pS4LmjrE9vejbiu1o0cVv6TwbyorA4JyWENh+WfPOekq9/BkrQu5d1E7VuxckJiAW3wzmeqQ6DPFsv6F/LndaNjeq64ZleQ2HQUZE7IGrXHyT3ay1ImA2YQNLBXyTR5AWcDU2eFJfdjBhiQr9w8GGEjZrb27z6w/Pe6W1MI+byNEjkMuyv73KxlIrgLRxxd5bxbx3PT0lQ1prl6agc+I/kG4Hwitj7kMFoc66B6WmNDCqfLyU59UcuPIrAcTqIdDvEnThWaQekPg22EpWC3FLbRD/bNr5FBBP2HMz6CWpa0iZqv8tXjQgkkzWnOxhOIWUHZJUi0FOK24MSwgGVDhwOPz6BQFifRKLM5uHqrH7AhdIxyd0KUkTgEYRShjKDSEvI1QgjgplpEv5/KbvEENVcWg1wSpPMVgcAv6Dt0zGRzRD0xh8P26uTXqD3W+nM6ISicmJwlpMueu8ouxyE7bgXcFSmE9Mhncp/X/Hs4DFtYUCS1mikgrabMhpGYG3fO+MJd4Cb00q/E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
