env:
  global:
    - secure: EF3RyyJHGgKFaxdTXSRDuScxkfPfyD+QLotKqmplsuqVhbRPGJZca2FTMCfZ/UEfJKG/HTgWJP2YpcnRVtSE1GFfP0yZLPqw/f0dz5JxMFLdm5qHM108lWi1w7utz41hkz3Svj7GkH93gCK2PQMhBshPPv5EGgfnBGLrgPytWYRMwrzUIktgfQZ6jBAjuN85NwZo8jVFaDCi4ZdHMU0oYVcSAkt3fKQRzkc3uI8hH7MeY6PQiXatftS0or574HCufhbgDnl5QlOFXUnUZY2I9ITKqstrVAIxKREaVhtGFkDXod8r+/iGAWEzha37qpOdO3dB0Nt4Y1JPaGRQNy9tigQJVLCi+yf/Hb8Z2kMzuhJaXNHj4/qA0HVv/xbeUEBiq/jH3jMzORUwDN9IRRRYb521agNAVD4upVo8q4pyJe6+Nv1JuRwOLeP+gaWH4hSg8ptyMWnmxfvosxUrcPkJmMZhKGpU7YWjKghOZpdExDTmfpSsug053RoKutRvsbAJEsfPNrqhoTswpX4CswZfPhsOadK/XeQMEyOjtw0TjzMW8aOp03pA0EdzZj6QDKIIJrfQumnK8t/wO2N1oJ1idAV2Z0kp7j55Ud3WnY1MyQDNVlNLuW2lJJRCDmvLBzK5fKz8uhWpWeZgBYKd63++AKhcDJCD8xWKgHo1kK9tJsY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
