env:
  global:
    - secure: j4CDbRoLxb6wfXH32O9lClkoESu0PjLZigyTJXOtg7KiXVhVRLVAlO2XpC/2zS9HCYl4QNVPSmLd8iGp2n1Xm0G/qW6cnn/x3Ye7FGXDyxGxfQOA3BFraFLh3b0MXPsTbaLl4r2YWjNkfSeMkoKMCMlSjxuien/zQWe05l7dm4yWs3M4PX+kH5tYAFSu+EInwWVcfHFJFitT4PFsQoyH7LD/IIzTj3IJmo9MZmvr3FbNmF77IIxIqP1GyiaDbmBvhh7GbjAA9PXHzmFeVlv5Zx4Obk17xEIbq/e5qzGsrXBGxXKIYKJXchxrtltOBpbELFILFwF6s+q9wPAMsw+Boro0RUXdhnwOzei1sYYCPbt3xkH3EASmzL/x2nFbTIqnOfVpIzode/ka0/Nmtl4Y1mPXWA43EtDqYvA067pofgjuurEx01usX8uUuyLrDCbATcl1q526oJ8FbTTa92X0gOToOjfeFIgFHhcRc+95POLR2c8Q5wpO4YHgTogOYb/6ytE7TCN3CMQxp87dDabWeeVLLa9QVxiKE41yHwJTZcR+3tZlZvmIwkT9U1rTAGEwoGWHD4a4Y1L5NKBzhyzFDe84vySDN+cE/9Sej8s+jZs1j/Qs4dNeOtZ9jNfjbWGSE/+Bwbw4dG+KA8Ps7Ha+YEUXxFIdS3FCRlLe4Np19ro=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
