env:
  global:
    - secure: VRuquq4cRNCx91CGMMvYb6KZ7hpWHMfM+sY7YZHfSZ3ZiQucEfFPLKIwhM8lJlJSME0sCaMYPC2H7VLDqfzClsNUiq4+vnLW28VuXTap+Dnat9Fl7h2whbwK1J10VHHqAThM7qCiVnz0z40qB3PDveWhHyTkrCXMUw37QOpLrkpWyQaSVGNGqIA+sNBYn7tlCN7dQQu8aj4bk84/8arUnELDtl4i3ucVVlH9bOE/LWp6Q1T5STH+9y/6O5JiTuGQ3HuzD7Fx4q2vE3PJ+3fDGKRY1sKcIsqtF/ZREl2KlJAD48+//DD9cUNrI/g4nKDkEKHnOTqX19KmEVq94YUAyfX0A3pcoNeMumGQanIBSTT8reORGRoL4SklvXVtpXqktKoVcHaoqqKgnbGIEmFVJUtHo2Y99qDm63r5kSy7V1vlU3EaBuTbgSOdFU6dZ0O6DZZxhVs+M15WT5Q4QpDOj9GW1q+Fnm2qDEaOtbVhix928j2SFaaMrhh4L1gCyCtTrTyyCdTytNRk0pCpnTX6UMYSJy+tiyLTQnGDW+XN6A+CD7GJIaWtE7CwvHvSt+ZREv0DrXE5dbS6TFu3igONG+Wm/pHPDC4fGdpi3j1mUtskhoazRekZV9QqZAFQjETNMvc4+Yuu+9bNnzraKhd4lTUGoLGQFuFlacern/mnax0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/UncheckyAds_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
